# Generated by Django 4.0.6 on 2022-07-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_about_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
