# Generated by Django 4.0.6 on 2022-07-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_about_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(null=True, verbose_name='Приглашение от пользователя')),
                ('user_who_add', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_with_add', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Friend', to=settings.AUTH_USER_MODEL, verbose_name='Друг')),
            ],
        ),
    ]
